---
- name: Uninstall Playbook of a AMQ Standalone Environment
  
    # remote install
  # hosts: fuse-environment
  
  # local install
  hosts: 127.0.0.1
  connection: local
  
  remote_user: amq
  gather_facts: true
  become: yes
  become_user: amq
  become_method: su
  roles:
    - { role: amq-uninstall }
    #- { role: fuse-uninstall, esb_name: 'esb02' }
